[versions]
kotlin = "unspecified"
ktx = "1.8.0"
appcompat = "1.3.1"
material = "1.4.0"
ext-junit = "1.1.3"
junit = "4.+"
espresso-core = "3.4.0"

[libraries]
android-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "ext-junit" }
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
junit-core = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
